api_platform:
    title: BileMo
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_client_items_per_page: true
    use_symfony_listeners: true
    collection:
        pagination:
            page_parameter_name: page
            items_per_page_parameter_name: limit
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
