services:

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ${APP_SLUG}_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    env_file:
      - .env.local
    depends_on:
      - php

  # Mariadb Service
  database:
    image: mariadb:latest
    container_name: ${APP_SLUG}_database
    restart: unless-stopped
    ports:
      - "5432:3306"
    environment:
      SERVICE_TAGS: ${APP_ENV}
      SERVICE_NAME: ${APP_SLUG}_database
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - /var/www/database:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network
    env_file:
      - .env.local

      # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_SLUG}_php
    restart: unless-stopped
    environment:
      SERVICE_NAME: ${APP_SLUG}_php
      SERVICE_TAGS: ${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network
    env_file:
      - .env.local
    depends_on:
      - database

# Docker Networks
networks:
  app_network:
    driver: bridge
